export const authConstants = {
    // USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    // USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    // USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE'
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT'
};

export const userConstants = {
    GET_REALTIME_USERS: 'GET_REALTIME_USERS',
    GET_REALTIME_MESSAGES: 'GET_REALTIME_MESSAGES'
}